[package]
name = "pcd-rs-derive"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "~1"
syn = { version = "~1", features = ["extra-traits"] }
quote = "~1"
