[package]
name = "pcd-rs"
version = "0.1.1"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Read PCD file format in Rust"
categories = ["parsing"]
documentation = "https://docs.rs/pcd-rs/0.1.0/pcd-rs/"
repository = "https://github.com/jerry73204/pcd-rs"
homepage = "https://github.com/jerry73204/pcd-rs"
license = "MIT"
license-file = "LICENSE"

[dependencies]
byteorder = "^1"
log = "^0.4"
# memmap = "^0"
